services:
  db:
    image: postgres:16-alpine
    container_name: pinstack-user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: userservice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pinstack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pinstack-user-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pinstack-network

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    container_name: pinstack-user-migrator
    environment:
      - ENV=dev
    volumes:
      - ./migrations:/app/migrations
      - ./config:/app/config
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pinstack-network
    command: ./migrator -command up

volumes:
  postgres_data:

networks:
  pinstack-network:
    driver: bridge 