env: "dev"

grpc_server:
  address: "0.0.0.0"
  port: 50051

database:
  username: "postgres"
  password: "admin"
  host: "user-db"
  port: "5432"
  db_name: "userservice"
  migrations_path: "./migrations"

redis:
  address: "redis"
  port: 6379
  password: ""
  db: 6
  pool_size: 10

prometheus:
  address: "0.0.0.0"
  port: 9101
