env: "dev"

http_server:
  address: "0.0.0.0:8000"
  timeout: "4s"
  idle_timeout: "60s"

database:
  username: "postgres"
  password: "admin"
  host: "user-db"
  port: "5432"
  db_name: "userservice"
  migrations_path: "./migrations"

jwt:
  secret: "my-secret"
  access_expires_at: "1m"
  refresh_expires_at: "5m"
